package com.ludusassistant.app.hero;
import android.content.Context; import org.json.JSONArray; import org.json.JSONObject; import java.util.*;
/** Version-aware public-data seed. Exact skill numerics remain client-verified rather than fabricated. */
public final class HeroRepository {
 private final List<Hero> heroes=new ArrayList<>(); public HeroRepository(Context c){seed();}
 private void seed(){heroes.clear();
  add("lion_dancer","Lion Dancer","S+","综合定位待验证","公开榜单S+"); add("love_marine","Love Marine","S+","综合定位待验证","公开榜单S+"); add("evil_eye","Evil Eye","S+","DPS/减益","输出与减益"); add("witch","Witch","S+","综合定位待验证","公开榜单S+"); add("mummy_warrior","Mummy Warrior","S+","综合定位待验证","公开榜单S+"); add("lich","Lich","S+","综合定位待验证","公开榜单S+"); add("pirate_queen","Pirate Queen","S+","综合定位待验证","公开榜单S+"); add("princess","Princess","S+","坦克/控制","前排承伤/控制"); add("storm","Storm","S+","DPS","高压持续输出"); add("pumpkin_jack","Pumpkin Jack","S+","综合定位待验证","公开榜单S+"); add("ice_witch","Ice Witch","S+","综合定位待验证","公开榜单S+"); add("cupid","Cupid","S+","综合定位待验证","公开榜单S+"); add("king_arthur","King Arthur","S+","综合定位待验证","公开榜单S+"); add("mako","Mako","S+","位移/控制","干扰敌方站位"); add("wizardess","Wizardess","S+","综合定位待验证","公开榜单S+"); add("buddy","Buddy","S+","综合定位待验证","社区常见核心"); add("verena","Verena","S+","综合定位待验证","公开榜单S+"); add("ghost_cat","Ghost Cat","S+","综合定位待验证","公开榜单S+"); add("yeti","Yeti","S+","综合定位待验证","公开攻略常见控制/输出"); add("sniper_girl","Sniper Girl","S+","综合定位待验证","公开榜单S+");
  String[] s={"Friday","Gambler","Tech Golem","Angel","Gunflower","Boaris","Chief","Jelly Knight","Electric Mage","Iron Tony","Leprechaun","Robo Santa","Muerta","Agent","Lava Girl","Little Red Cap","Witch Doctor","Gunbot","Alice","Uruk","Firestarter","Monkey King","Druid","Galaction","Sandy Turmoil","Sword-Man"}; for(String n:s)add(id(n),n,"S","综合定位待验证","公开榜单S");
  String[] a={"Warlock","Minotaur","Totem","Gunslinger","Rocky","Gorgon","Succubus","Snoozemander","Easter Bunny","Duckwing","Pop Star","Gingerbread Man","Crystallix","Brewmaster","Turkey Master","Ludusman","Drago","Draco","Griffon","Captain Nemo","Vampire"}; for(String n:a)add(id(n),n,"A","综合定位待验证","公开榜单A");
  String[] b={"Plague Doctor","Slime","Franken","Axe Thrower","Samurai","Arachne","Bastion","Crusader","Shaman","Executioner","Paladin","Genie","Jester","Mr. Gray","Gearhead","Fencer","Valkyrie","Treant","Imp","Nightmare","Vulcan","Aqua","Trickster","Mimic","Kitsune"}; for(String n:b)add(id(n),n,"B","综合定位待验证","公开榜单B");
  String[] c={"Viking","Huntress","Saboteur","Fairy","Cannoneer"}; for(String n:c)add(id(n),n,"C","综合定位待验证","公开榜单C");
 }
 private String id(String n){return n.toLowerCase(Locale.ROOT).replace(" ","_").replace("-","_");}
 private void add(String id,String name,String tier,String role,String note){String ability="技能详情：当前公开资料未给出可可靠复现的完整数值，助手将在客户端观测/版本资料确认后覆盖；不虚构数值。"; heroes.add(new Hero(id,name,"未分类","未分类",tier,role,ability,"强度参考："+tier+"；具体技能、星级成长和阵营以当前客户端为准。", "public-2026-07"));}
 public List<Hero> list(){return Collections.unmodifiableList(heroes);} public JSONArray all(){return filter(null,null,null);} public JSONArray filter(String race,String faction,String rarity){JSONArray a=new JSONArray(); for(Hero h:heroes){if(race!=null&&!race.isEmpty()&&!race.equals(h.race))continue;if(faction!=null&&!faction.isEmpty()&&!faction.equals(h.faction))continue;if(rarity!=null&&!rarity.isEmpty()&&!rarity.equals(h.rarity))continue;try{a.put(toJson(h));}catch(Exception ignored){}}return a;} private JSONObject toJson(Hero h)throws Exception{return new JSONObject().put("id",h.id).put("name",h.name).put("race",h.race).put("faction",h.faction).put("rarity",h.rarity).put("role",h.role).put("ability",h.ability).put("gameplay",h.gameplay).put("version",h.version);}
 public String grouped(){Map<String,List<Hero>> m=new LinkedHashMap<>();for(Hero h:heroes)m.computeIfAbsent(h.rarity,k->new ArrayList<>()).add(h);StringBuilder s=new StringBuilder();for(Map.Entry<String,List<Hero>> e:m.entrySet()){s.append("【强度层级：").append(e.getKey()).append("】\n");for(Hero h:e.getValue())s.append("• ").append(h.name).append(" · ").append(h.role).append("\n");}return s.toString();}
 public String detail(String id){for(Hero h:heroes)if(h.id.equals(id))return "【"+h.name+"】\n稀有度/榜单："+h.rarity+"\n定位："+h.role+"\n技能："+h.ability+"\n玩法："+h.gameplay;return "未找到英雄";}
}
